let express=require("express")
let mongoose=require("mongoose")
let cors=require("cors")
let bodyParser=require("body-parser")
const route = require("./routes/rt")
mongoose.connect("mongodb://127.0.0.1:27017/appointment").then(()=>{
    console.log("db ok")
})
let app=express()
app.use(cors())
app.use(express.json())
app.use(bodyParser.urlencoded({"extended":true}))
app.use("/uimgs",express.static("./userimgs"))
app.use("/pimgs",express.static("./prodimgs"))
app.use("/",route)
app.listen(5000)